In [25]:
# Importing required modules

import pandas as pd
from bs4 import BeautifulSoup
import requests
import lxml

Collecting lxmlNote: you may need to restart the kernel to use updated packages.

  Using cached lxml-4.9.2-cp311-cp311-win_amd64.whl (3.8 MB)
Installing collected packages: lxml
Successfully installed lxml-4.9.2

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
# Fetching contents from the required website 

url='https://www.worldometers.info/coronavirus/'
webpage=requests.get(url=url)
soup=BeautifulSoup(webpage.content)

SyntaxError: positional argument follows keyword argument (340677528.py, line 4)

In [14]:
# Getting table
table=soup.find('table',{'class': 'table'})
print(table)

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">New<br>Recovered</br></th>
<th width="30">Active<br>Cases</br></th>
<th width="30">Serious,<br>Critical</br></th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>125,612,764</td>
<td></td>
<td>1,621,382</td>
<td></td>
<td>121,161,103</td>
<td>+1,353</td>
<td>2,830,279</td>
<td>7,174</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>215,198,643</td>
<td>+11,155</td>
<td>1,540,436</td>
<td>+10</td>
<td>199,798,623</td>
<td>+18,906</td>
<td>13,859,584</td>
<td>15,568</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>247,721,008</td>
<td></td>
<td>2,029,638</td>
<td></td>
<td>243,367,976</td>
<td>+29,649</td>
<td>2,323,394</td>
<td>6,456</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>68,323,619</td>
<td></td>
<td>1,352,514</td>
<td></td>
<td>66,398,207</td>
<td></td>
<td>572,898</td>
<td>10,156</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>13,977,747</td>
<td></td>
<td>26,606</td>
<td></td>
<td>13,822,867</td>
<td></td>
<td>128,274</td>
<td>63</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,809,970</td>
<td></td>
<td>258,662</td>
<td></td>
<td>12,080,364</td>
<td></td>
<td>470,944</td>
<td>548</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>683,644,472</td>
<td>+11,155</td>
<td>6,829,253</td>
<td>+10</td>
<td>656,629,846</td>
<td>+49,886</td>
<td>20,185,373</td>
<td>39,965</td>
<td>87,705</td>
<td>876.1</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">106,163,408</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,154,353                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">103,889,389</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,119,666</td>
<td style="font-weight: bold; text-align:right">2,008</td>
<td style="font-weight: bold; text-align:right">317,090</td>
<td style="font-weight: bold; text-align:right">3,448</td>
<td style="font-weight: bold; text-align:right">1,173,341,050</td>
<td style="font-weight: bold; text-align:right">3,504,548</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>290</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,344</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,709,676</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">530,848                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,166,925</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">11,903</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,785</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">921,161,295</td>
<td style="font-weight: bold; text-align:right">654,870</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,650</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">8</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">39,782,589</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">165,609                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,473,503</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">143,477</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">606,585</td>
<td style="font-weight: bold; text-align:right">2,525</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>396</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,188</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,347,963</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">170,727                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,071,800</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+7,600</td>
<td style="text-align:right;font-weight:bold;">105,436</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">457,157</td>
<td style="font-weight: bold; text-align:right">2,035</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>491</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,257</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">37,258,663</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">700,239                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">309,263</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">173,012</td>
<td style="font-weight: bold; text-align:right">3,252</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>308</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,436</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,441,444</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">73,825                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">21,717,039</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">11,650,580</td>
<td style="font-weight: bold; text-align:right">68</td>
<td style="font-weight: bold; text-align:right">266,286</td>
<td style="font-weight: bold; text-align:right">588</td>
<td style="font-weight: bold; text-align:right">97,980,002</td>
<td style="font-weight: bold; text-align:right">780,190</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,701</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">92,771</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">30,809,762</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+11,039</td>
<td style="font-weight: bold; text-align:right;">34,255                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+10</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,600,486</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+9,328</td>
<td style="text-align:right;font-weight:bold;">175,021</td>
<td style="font-weight: bold; text-align:right">143</td>
<td style="font-weight: bold; text-align:right">600,230</td>
<td style="font-weight: bold; text-align:right">667</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,498</td><td>3</td>
<td style="font-weight: bold; text-align:right">215</td>
<td style="font-weight: bold; text-align:right">0.2</td>
<td style="font-weight: bold; text-align:right">3,410</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,673,442</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">188,933                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,345,910</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">138,599</td>
<td style="font-weight: bold; text-align:right">105</td>
<td style="font-weight: bold; text-align:right">426,025</td>
<td style="font-weight: bold; text-align:right">3,135</td>
<td style="font-weight: bold; text-align:right">269,569,208</td>
<td style="font-weight: bold; text-align:right">4,473,230</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>319</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,300</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,448,729</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">209,396                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,194,909</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,611</td>
<td style="text-align:right;font-weight:bold;">44,424</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">356,927</td>
<td style="font-weight: bold; text-align:right">3,057</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>327</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">649</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">22,614,774</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">397,179                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">21,970,063</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">247,532</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">155,102</td>
<td style="font-weight: bold; text-align:right">2,724</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>367</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,698</td>
</tr>
<tr style="">

In [27]:
df=pd.read_html(str(table))
df=pd.DataFrame(df[0])

ImportError: lxml not found, please install it